[build]
  publish = "frontend/dist"
  command = "cd frontend && npm ci && npm run build"

[build.environment]
  NODE_VERSION = "20"

# Redirects for SPA routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# API proxy to external backend (when using hybrid deployment)
[[redirects]]
  from = "/api/*"
  to = "https://your-backend-url.railway.app/:splat"
  status = 200
  force = true

# Headers for security
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Cache static assets
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Environment variables (set in Netlify dashboard)
# VITE_API_BASE_URL = "https://your-backend-url.railway.app"
# VITE_APP_ENV = "production"
